### ISSUE TITLE
项目启动后报这个错 是不是有的依赖版本不对

### ISSUE THREAD

**Issue by DroganC** [aisuda/amis-widget-cli#11]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/32896700/205053179-40c5ebb4-6b3c-4e59-b6df-86e1cc6c6591.png">
脚手架版本2.2.12
执行amis init -t=react生成的项目
能否提供一个最新的可运行工程

**Comment by wibetter** [comment]
是因为rc-input-number@7.4.0做了不兼容升级导致的，目前已处理，请将amis-widget-cli升级到3.0.0-beta.12。
