### ISSUE TITLE
3.0.2编辑器不显示amis-widget注册的自定义组件

### ISSUE THREAD

**Issue by wleven** [aisuda/amis-widget-cli#13]
amis-widget-cli 从3.0.0-beta.13升级到3.0.2

amis-widget注册的自定义组件在编辑器中不显示了

而且控制台没有任何输出/错误信息

amis-widget 版本2.0.5和3.0.6都无任何错误信息

**Comment by wibetter** [comment]
npm list amis 看下amis的版本是多少？

**Comment by wleven** [comment]
> npm list amis 看下amis的版本是多少？

2.5.3-beta.0

**Comment by wibetter** [comment]
看下用到的amis-widget版本是多少，需要注意下：
2.0 版本支持 amis 和 amis-editor 的任何版本；
3.0.0 以上版本需要 amis 2.5.2-beta.0 以上版本， amis-editor 5.2.1-beta.32 以上版本。

**Comment by wleven** [comment]
> 看下用到的amis-widget版本是多少，需要注意下： 2.0 版本支持 amis 和 amis-editor 的任何版本； 3.0.0 以上版本需要 amis 2.5.2-beta.0 以上版本， amis-editor 5.2.1-beta.32 以上版本。

amis-widget 版本2.0.5和3.0.6 都测试过了，不显示也没有报错

**Comment by wibetter** [comment]
出现这类问题，一般就是因为amis-widget 的版本和amis-editor的版本不匹配，比如amis-widget3.0.6 用到的还是amis-editor 5.2.1-beta.32 以下的版本。

**Comment by wleven** [comment]
> 出现这类问题，一般就是因为amis-widget 的版本和amis-editor的版本不匹配，比如amis-widget3.0.6 用到的还是amis-editor 5.2.1-beta.32 以下的版本。

那2.0.5也不行啊，2.0.5不是支持任何版本？

**Comment by wibetter** [comment]
2.0.5也不没正常显示自定义组件的话，那可能就是写的有问题了。参照这个文档，对比下哪儿没写对：https://baidu.gitee.io/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E5%BC%80%E5%8F%91amis%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85
