### ISSUE TITLE
使用自定义组件

### ISSUE THREAD

**Issue by zhanggq1014** [aisuda/amis-widget-cli#14]
请问如何把脚手架生成的自定义组件，引用到自己的项目中的amis渲染出来，还有如何引入到自己的编辑器

**Comment by wibetter** [comment]
amis-widget-cli构建出来的自定义组件主要是在爱速搭平台使用的，具体使用方式请见：https://aisuda.bce.baidu.com/aisuda-docs/NPM%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85/%E5%BC%80%E5%8F%91amis%E7%BB%84%E4%BB%B6%E6%89%A9%E5%B1%95%E5%8C%85。
如果想引入到组件的编辑器（amis-editor）,只需要在加载编辑器的时候，也加载这些构建后的js和css文件。
