### ISSUE TITLE
自己项目中如何让amis-editor自动识别amis-widget

### ISSUE THREAD

**Issue by hbkgoing** [aisuda/amis-widget-cli#15]
爱速搭文档中说， 爱速搭会自动识别 amis-widget-cli构建产物中package.json中的amis-widget配置项。请问如何让自己项目中的amis-editor也能自动识别amis-wdiget

**Comment by wibetter** [comment]
如果是单独使用amis-editor，就没必要使用amis-widget了。amis-widget主要是在平台端使用，方便平台扩展自定义组件。
