### ISSUE TITLE
希望支持 historyApiFallback 可配置

### ISSUE THREAD

**Issue by jokingzhang** [aisuda/amis-widget-cli#16]
在开发 amis 的时候，想使用 BrowserRouter，希望可以设置 historyApiFallback 方便调试

**Comment by jokingzhang** [comment]
![image](https://github.com/aisuda/amis-widget-cli/assets/10766546/5449fdc7-e0d2-46b2-9d54-bca681fdeeee)
现在访问404

**Comment by hooli67** [comment]
一样的问题， 你解决了没有！

**Comment by jokingzhang** [comment]
> 一样的问题， 你解决了没有！

没有，准备用 hash 了

**Comment by hooli67** [comment]
遭不住啊，不支持BrowserRouter

**Comment by wibetter** [comment]
amis-widget-cli 已默认支持 history 路由模式，无需额外配置。你也可以拉取amis-editor-demo最新代码本地验证效果：https://github.com/aisuda/amis-editor-demo/commit/70e535540bec26a404b3945b625939dd2a244c67
