### ISSUE TITLE
vue3的setup 写在script 标签中，现在是还不支持吗？

### ISSUE THREAD

**Issue by ZephyrTan** [aisuda/amis-widget-cli#18]

**Comment by ZephyrTan** [comment]
> @ZephyrTan 请问你说的script 标签是指vue的还是html的？

vue的，vue3直接写<script setup lang='ts'> ，我试了这种方式好像不行，setup中return是可以的

**Comment by wibetter** [comment]
@ZephyrTan 已提供 vue3 组合式API开发模式示例，欢迎试用：https://github.com/aisuda/vue3-amis-custom-widget/tree/feat-vue3-demo。
