### ISSUE TITLE
期望dist构建出一个JS文件

### ISSUE THREAD

**Issue by jiasijiamn** [aisuda/amis-widget-cli#20]
每个自定义组件都构建出一个js， 每次都得单独引入，怎么能打成一个js文件呢？

**Comment by wibetter** [comment]
这个你可以自行调整amis.config.js配置文件实现的，比如 build2lib 的入口配置改成以下方式就可以打包成一个js：
<img width="884" alt="image" src="https://github.com/aisuda/amis-widget-cli/assets/11958920/63b2a603-c2d1-4955-bd81-005fa6777ebd">
