### ISSUE TITLE
build2lib 打出来的包在浏览器报错 ReferenceError: require is not defined

### ISSUE THREAD

**Issue by wubin1989** [aisuda/amis-widget-cli#21]
build2lib 打出来的包在浏览器报错 ReferenceError: require is not defined

**Comment by wibetter** [comment]
@wubin1989 build2lib构建后的产物，默认会剔除掉第三方依赖模块，如果要引入其他项目，还需要进行一次构建方可正常使用。
特别说明：构建后的产物非umd模块，不能直接在浏览器中使用。如果需要在浏览器端使用，可以调整构建配置，将第三方依赖模块也打包进来。
