### ISSUE TITLE
注册不上amis  组件提示“Error: 找不到对应的渲染器”

### ISSUE THREAD

**Issue by Hookuku** [aisuda/amis-widget-cli#22]
![image](https://github.com/aisuda/amis-widget-cli/assets/88571092/1e7019bb-2712-4891-a0e1-f18e2712eda8)

**Comment by swieer** [comment]
amis3.6.4可以渲染，升级到6.3以上就有这个问题

**Comment by swieer** [comment]
@wibetter 如图，我用注释了的getSchemaTpl方法不能渲染，只能是基本的方法
![QQ截图20240604143932](https://github.com/aisuda/amis-widget-cli/assets/6882986/a25c1b56-b1e0-40f2-a7da-c6e687294e93)

**Comment by wibetter** [comment]
@swieer 请问你的getSchemaTpl是从哪里import的过来的，是从amis-widget中引入的吗？如果是，应该是能正常渲染的，
<img width="727" alt="image" src="https://github.com/aisuda/amis-widget-cli/assets/11958920/33f5269b-8b51-4b15-999c-48b816413536">
<img width="603" alt="image" src="https://github.com/aisuda/amis-widget-cli/assets/11958920/ed4b119f-49e5-4933-95b1-1260da8028d8">

**Comment by swieer** [comment]
> @swieer 请问你的getSchemaTpl是从哪里import的过来的，是从amis-widget中引入的吗？如果是，应该是能正常渲染的， 
getSchemaTpl我从npm引入amis-widget 3.2.2, 从amis-widget build后的文件index.umd.js直接引入都试过,,都不能渲染，amis的版本从6.3到6.4,6.5都试了，都是找不到渲染器

**Comment by swieer** [comment]
![image](https://github.com/aisuda/amis-widget-cli/assets/6882986/c81aa9c9-7e81-4e09-a669-a9c0b00e2932)

**Comment by swieer** [comment]
@wibetter ，在自组件里，怎么写事件的配置，看amis-editor里，需要获取manager,context,
但自定义组件里不知道怎么写，下面的
···
{
        title: '事件',
        className: 'p-none',
        body: [
          getSchemaTpl('eventControl', {
            name: 'onEvent',
            ...getEventControlConfig(this.manager, context)
          })
        ]
      }
···

**Comment by wibetter** [comment]
@swieer 可以参考amis-editor plugin中的写法，在plugin设置onEvent的可视化配置。
