### ISSUE TITLE
amis init -t=react 卡着不动

### ISSUE THREAD

**Issue by imlida** [aisuda/amis-widget-cli#4]
The authenticity of host 'github.com (140.82.114.3)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
<img width="598" alt="image" src="https://user-images.githubusercontent.com/5794390/157627704-abd2bbc6-44b6-4bf3-9d15-b4c351dbac76.png">

**Comment by wibetter** [comment]
可能时.ssh 文件夹缺少known_hosts文件，直接输入yes 回车 试一下看看，

**Comment by wibetter** [comment]
也可以直接从https://github.com/aisuda上clone对应的组件模板：
![image](https://user-images.githubusercontent.com/11958920/157697279-7e8257a9-0589-4b09-818a-f8ce4f2658f2.png)

**Comment by wibetter** [comment]
自定义组件模板存放在 Github，由于国内网络环境问题，可能下载失败。如果初始化组件失败请尝试如下措施：
1、在设备或路由器的网络设置中增加 DNS（如：8.8.8.8，使用Google DNS的主 DNS 服务器）；
2、在设备中增加固定的 hosts（如：140.82.113.4 github.com）

**Comment by wibetter** [comment]
ssh-keyscan github.com >> ~/.ssh/known_hosts

**Comment by wibetter** [comment]
目前已提供一种更快的安装模式：amis init -m=copy，可以毫秒级初始化自定义组件。
