### ISSUE TITLE
amis init 出错

### ISSUE THREAD

**Issue by peterleeee** [aisuda/amis-widget-cli#8]
在node 14 16 上都试过了，没有别的提示，就一个红色的X
![image](https://user-images.githubusercontent.com/23148140/172601615-da58a120-6bee-42f3-bb5f-aa5286a26bf4.png)

**Comment by wibetter** [comment]
自定义组件模板存放在 Github，由于国内网络环境问题，可能下载失败。如果初始化组件失败请尝试如下措施：
1、在设备或路由器的网络设置中增加 DNS（如：8.8.8.8，使用Google DNS的主 DNS 服务器）；
2、在设备中增加固定的 hosts（如：140.82.113.4 github.com）

**Comment by wibetter** [comment]
目前已提供一种更快的安装模式：amis init -m=copy，可以毫秒级初始化自定义组件。
